# Generated by Django 3.2.2 on 2021-05-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_remove_students_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='profile_pic',
            field=models.FileField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
